// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfHlpgP1xsw0mvW4_hB5nEcSgqtYCv6ds',
    appId: '1:356311657345:web:f3163cb3faad076e07d680',
    messagingSenderId: '356311657345',
    projectId: 'reddit-clone-tutorial-357f6',
    authDomain: 'reddit-clone-tutorial-357f6.firebaseapp.com',
    storageBucket: 'reddit-clone-tutorial-357f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTtm5RCE_9k-36crpKHm0veT1BCeoiEng',
    appId: '1:356311657345:android:427778a8c178ee0d07d680',
    messagingSenderId: '356311657345',
    projectId: 'reddit-clone-tutorial-357f6',
    storageBucket: 'reddit-clone-tutorial-357f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5jzcQBj0c44l47s844zN7IPOcVlVF2WE',
    appId: '1:356311657345:ios:0522e4ebf7e548d907d680',
    messagingSenderId: '356311657345',
    projectId: 'reddit-clone-tutorial-357f6',
    storageBucket: 'reddit-clone-tutorial-357f6.firebasestorage.app',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5jzcQBj0c44l47s844zN7IPOcVlVF2WE',
    appId: '1:356311657345:ios:0522e4ebf7e548d907d680',
    messagingSenderId: '356311657345',
    projectId: 'reddit-clone-tutorial-357f6',
    storageBucket: 'reddit-clone-tutorial-357f6.firebasestorage.app',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfHlpgP1xsw0mvW4_hB5nEcSgqtYCv6ds',
    appId: '1:356311657345:web:e90171170d3633e607d680',
    messagingSenderId: '356311657345',
    projectId: 'reddit-clone-tutorial-357f6',
    authDomain: 'reddit-clone-tutorial-357f6.firebaseapp.com',
    storageBucket: 'reddit-clone-tutorial-357f6.firebasestorage.app',
  );
}
